[Feature/#32/ProjectDetailTop] 프로젝트 상세정보 요약정보 구현
side-peek/sidepeek_frontend pull request #48
Opened 2024-02-25 10:31 UTC by Whoknow77

## #️⃣연관된 이슈

#32 

## 💡 핵심적으로 구현된 사항

<img width="1795" alt="image" src="https://github.com/side-peek/sidepeek_frontend/assets/106851561/d3c2fb9c-2895-4910-8764-3f7fbf1a485b">

- swiper.js를 이용해 이미지 슬라이드를 구현
- UI 구현
- 클립보드 구현(현재 링크 복사)

## ➕ 그 외에 추가적으로 구현된 사항

## 🤔 테스트,검증 && 고민 사항
- 반응형, 좋아요 버튼 요청 등은 따로 이슈를 만들어서 구현하려 합니다.
- 파일 분리가 좀 안된것같은데 관련해서 말씀해주시면 감사하겠습니다!!

### 📌 PR Comment 작성 시 Prefix for Reviewers

2024-02-25 11:06 UTC, whdgur5717 requested changes
일단
- package.json이랑 lock.json 파일 변경할 경우 따로 commit으로 묶고, 버전네임 붙여서 관리하기로 했는데 지금 어디 commit에 있는지도 잘 못찾겠네요.. 발견하시면 커밋네임 수정 부탁드립니다(v1로 하시면 됩니다)
- build 실패한 부분 상단 Tab에 Commits 들어가시면 X버튼으로 되어있는 커밋 있을텐데 그 부분에 에러메시지 있어서 그거보고 수정 부탁드립니다!

2024-02-25 11:45 UTC, Whoknow77 commented on src/pages/ProjectDetailPage/hooks/query/useProjectDetail.ts
> +export default useProjectDetail
> P1 : 여기서는 API가 만들어졌다고 생각하고 그에 맞게 query문을 만들어야 나중에 수정 안할 수 있습니다!

아 실제로 props를 받아서 projectId로 넘기라는 말씀이신거죠??

2024-02-25 12:24 UTC, Whoknow77 commented
> package.json이랑 lock.json 파일 변경할 경우 따로 commit으로 묶고, 버전네임 붙여서 관리하기로 했는데 지금 어디 commit에 있는지도 잘 못찾겠네요.. 발견하시면 커밋네임 수정 부탁드립니다(v1로 하시면 됩니다)
- 맞네요ㅠ 일단 커밋 내역은 찾았는데 이미 원격저장소에 올라가서 다음부터 주의해야겠네요 ㅠ
> build 실패한 부분 상단 Tab에 Commits 들어가시면 X버튼으로 되어있는 커밋 있을텐데 그 부분에 에러메시지 있어서 그거보고 수정 부탁드립니다!
- PR올리고 바로 수정했습니다!
> 스타일 때문에 코드가 너무 길어져서 어떤 내용인지를 찾는데에 시간이 많이 걸리는 것 같습니다, 반복되는 스타일도 많아서 이 부분은 따로 컴포넌트화 해주시는 게 좋을 것 같습니다!
> 밑에 리뷰에서도 말씀드렸듯이, 합성 컴포넌트 방식 한번 고려해보시면 좋을 것 같습니다!
- 지금 컴포넌트 관리하는 방식이 좀 맘에 안들었는데 한번 공부해보고 적용해보겠습니다!

2024-02-25 14:26 UTC, wdgWon approved these changes
고생 많으셨습니다!! 👍👍
에디터도 힘드실텐데 스와이퍼까지 알아보시느라 진짜 고생하셨어요 ㅠㅠㅠ
전체 코드가 너무 깔끔해서 놀랐습니다!
구현된 화면도 정상 작동하고 이후 기능들이 추가되면 꽤나 멋있을 것 같네요!
 
> 파일 분리가 좀 안된것같은데 관련해서 말씀해주시면 감사하겠습니다!!
- 파일 분리 너무 잘하셨는데 어디서 그렇게 느끼셨는지...?

> 버튼을 사용할때 보통 backgorund을 none으로 하고 스타일을 각자 알맞게 하게 될 것 같은데 전역으로 backgorund:none과 hover시 스타일 속성을 선언하는것은 어떤가요?
- 일단 버튼의 `background`를 `none`으로 설정하는 경우가 저는 잘 없었어서... 다른 컴포넌트들에 영향이 가지 않는다면 좋습니다!

2024-02-25 14:26 UTC, wdgWon commented on src/pages/ProjectDetailPage/components/ProjectDetailSummaryContent/ProjectDetailSummaryRight.tsx
> +      </StyledSwiper>
와 훈오님 이거 하시느라 엄청 고생하셨겠다...
look good to me 웬만하면 안하려고 하는데
덕분에 스와이퍼 사용법 알아가요~

2024-02-25 14:26 UTC, wdgWon commented on src/pages/ProjectDetailPage/components/ProjectDetailSummaryContent/ProjectDetailSummaryRight.tsx
> +        zIndex="5"
P3 : zIndex는 전역에서 상수로 관리하는게 좋을 것 같습니다!
저도 헤더에 반영 안하긴 했네요... ㅎㅎ;

2024-02-25 14:26 UTC, wdgWon commented on src/types/domain/apiDomain.d.ts
> +// 원래 그게 맞긴해요 일단 제가 메모해놓을게요
P3 : 열심히 하시는 모습 본받아 갑니다~

2024-02-26 04:52 UTC, Whoknow77 commented on src/pages/ProjectDetailPage/mocks/index.ts
> +]
> P3 : 그리고 해당 데이터를 못 불러왔을 경우에 대한 코드도 추가해서 그에 맞게 어떤 컴포넌트를 보여줄지도 만들어보면 좋을 것 같습니다! 아니면 errorboundary 써도 좋을 것 같네요

넵! 이 부분은 페이지 전체를 만들고 넣으려고 했습니다

2024-02-26 04:54 UTC, Whoknow77 commented on src/pages/ProjectDetailPage/components/ProjectDetailSummaryTop/ProjectDetailSummaryTop.tsx
> +        />
> P3 : 비슷한 style의 IconButton이 icon props만 다르다면, IconButton을 따로 컴포넌트로 만들고 어떤 icon 들어갈지만 배열로 관리해서 map 돌리면 나중에 추가하기도 편할 것 같습니다!

방향부분도 다르긴한데 따로 빼니까 확실히 편안하네요 감사합니다

2024-02-26 04:56 UTC, Whoknow77 commented on src/pages/ProjectDetailPage/components/ProjectDetailSummaryContent/ProjectDetailSummaryRight.tsx
> +      </StyledSwiper>
> 와 훈오님 이거 하시느라 엄청 고생하셨겠다... look good to me 웬만하면 안하려고 하는데 덕분에 스와이퍼 사용법 알아가요~

문서도 잘 나와있어서 구현할 수 있었습니다..! 근데 살짝 까다로웠던건 navigation 버튼을 이동하려면 원래있던 버튼을 삭제하고 직접 만들어야한다는 점이었습니다..

2024-02-26 05:45 UTC, Whoknow77 commented on src/pages/ProjectDetailPage/components/ProjectDetailSummaryTop/ProjectDetailSummaryTop.tsx
> +        />
> P3 : 비슷한 style의 IconButton이 icon props만 다르다면, IconButton을 따로 컴포넌트로 만들고 어떤 icon 들어갈지만 배열로 관리해서 map 돌리면 나중에 추가하기도 편할 것 같습니다!

관련해서 컴포넌트를 나누는 것 까지는 좋았는데 막상 따로 배열로 관리하려니까 props가 다양하기도 하고, 동적인 props를 받아야해서 안에 두기에는 가독성을 해치다보니까 그냥 두었습니다!

2024-02-26 06:03 UTC, miloul reviewed
안녕하세요 훈오님 

컴포넌트로 최대한 분리하려고 고민하신게 보이는 것 같습니다 👍👍
버튼 전역 스타일 설정 좋습니다
자잘하게 몇가지 남깁니다 ㅎㅎ

고생하셨습니다! 👍👍

2024-02-26 06:03 UTC, miloul commented on src/pages/ProjectDetailPage/components/ProjectDetailSummaryTop/ProjectDetailSummaryTop.tsx
> +        />
P3; 진짜 별거 아니긴 한데.. 댓글 아이콘이 선이 굵어 그런지 저한테는 좀 커보여서.. `2.4rem`~`2.5rem`으로 조금 줄여주시면 좋을 것 같습니다

2024-02-26 06:25 UTC, Whoknow77 commented on src/pages/ProjectDetailPage/components/ProjectDetailSummaryTop/ProjectDetailSummaryTop.tsx
> +        />
> P3; 진짜 별거 아니긴 한데.. 댓글 아이콘이 선이 굵어 그런지 저한테는 좀 커보여서.. `2.4rem`~`2.5rem`으로 조금 줄여주시면 좋을 것 같습니다

그러게요.. 하트는 정상인데 애는 좀 굵게보이네요ㅠ 아예 아이콘을 얇은거로 바꾸고싶은데 마땅한게 없어서 일단 말씀해주신대로 사이즈를 줄여보도록 하겠습니다!

2024-02-26 06:26 UTC, Whoknow77 commented on src/pages/ProjectDetailPage/components/ProjectDetailSummaryTop/ProjectDetailSummaryTop.tsx
> +  return (
> ASK; 스크롤 시 고정되는 것은 나중에 추가되는 건가용?

사실 까먹고있었습니다.. 나중에 추가하려고 합니다!!

2024-02-27 03:19 UTC, hellosonic-r approved these changes
훈오님 구현하시느라 고생하셨습니다.
개인적으로는 컴포넌트 분리가 잘 되어있어서 전체적인 구조를 파악하기 쉬웠던 것 같네용

2024-02-27 03:19 UTC, hellosonic-r commented on src/pages/ProjectDetailPage/components/ProjectDetailSummary.tsx
> +    <Box bg="#f5f5f5">
P5; 
이부분 아마 인지하고 있을거라 생각하는데 theme에 분리하는 게 좋을 것 같습니다! 나중에 바꾸실 생각이었다면 죄송합니다

2024-02-27 03:19 UTC, hellosonic-r commented on src/pages/ProjectDetailPage/components/ProjectDetailSummary.tsx
> +              githubUrl={githubUrl}
저도 이번에 알게 된 내용인데 저렇게 전달해야하는 props가 늘어날 경우 아래와 같이 전달이 가능하다고 합니다. 혹시 알고계셨다면 죄송요 ㅎㅎ ;;
```typescript
<ProjectDetailSummaryContent {...{overviewImgUrl, overview, deployUrl, githubUrl, }} />
```

2024-02-27 05:43 UTC, Whoknow77 commented on src/pages/ProjectDetailPage/components/ProjectDetailSummary.tsx
> +              githubUrl={githubUrl}
> 저도 이번에 알게 된 내용인데 저렇게 전달해야하는 props가 늘어날 경우 아래와 같이 전달이 가능하다고 합니다. 혹시 알고계셨다면 죄송요 ㅎㅎ ;;
> 
> ```ts
> <ProjectDetailSummaryContent {...{overviewImgUrl, overview, deployUrl, githubUrl, }} />
> ```

몰랐었는데 감사합니다..ㅎㅎ

2024-02-28 01:56 UTC, merged